name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile the project
        run: mvn -B compile

      - name: Run unit tests
        run: mvn -B test

      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc

      - name: Check Javadoc output
        run: |
          if [ -d "target/site/apidocs" ]; then
            echo "✅ Javadoc generated successfully."
          else
            echo "❌ Javadoc generation failed."
            exit 1
          fi

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
